# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielens_app', '0002_auto_20170321_2254'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='rater',
        #     name='zipcode',
        #     field=models.IntegerField(default=12345),
        #     preserve_default=False,
        
    ]
