# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:58
from __future__ import unicode_literals
from django.db import migrations
from ..models import Movie, Rater
import csv


class Migration(migrations.Migration):
    def load_movies(apps, schema_editor):
        with open('u.item', 'r', encoding='latin_1') as f:
            reader = csv.reader(f, delimiter="|")
            for row in reader:
                x = Movie()
                x.title = row[1]
                x.release_date = row[2]
                x.id = row[0]
                x.save()

    def load_raters(apps, schema_editor):
        with open('u.user', 'r') as f:
            reader = csv.reader(f, delimiter='|')
            for row in reader:
                x = Rater()
                x.occupation = row[3]
                x.age = row[1]
                x.gender = row[2]
                x.zipcode = row[4]
                x.id = row[0]
                x.save()

    # def load_ratings(apps, schema_editor):
    #     with open('u.data', 'r') as f:
    #         reader = csv.reader(f, delimiter='\t')
    #         for row in reader:
    #             x = Rating()
    #             print(row[1])
    #             x.movie = Movie.objects.get(id = row[1])[0]
    #             x.rater = Rater.objects.get(id = row[0])[0]
    #             x.rating = row[2]
    #             x.timestamp = row[3]
    #             x.save()

    dependencies = [
        ('movielens_app', '0003_auto_20170321_2255'),
    ]

    operations = [
        migrations.RunPython(load_movies),
        migrations.RunPython(load_raters),
        # migrations.RunPython(load_ratings),
    ]
