# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movielens_app', '0004_auto_20170321_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rater',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
