# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:07
from __future__ import unicode_literals
import csv
from django.db import migrations
from ..models import Movie, Rating, Rater


class Migration(migrations.Migration):
    def load_ratings(apps, schema_editor):
        with open('u.data', 'r') as f:
            reader = csv.reader(f, delimiter='\t')
            for row in reader:
                x = Rating()
                x.movie = Movie.objects.get(id=row[1])
                x.rater = Rater.objects.get(id=row[0])
                x.rating = row[2]
                x.timestamp = row[3]
                x.save()

    dependencies = [
        ('movielens_app', '0005_auto_20170322_1748'),
    ]

    operations = [
        migrations.RunPython(load_ratings),
    ]
