# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:07
from __future__ import unicode_literals
# import names
from django.db import migrations
from ..models import Rater
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    def load_users(apps, schema_editor):
        rater_list = Rater.objects.all()
        for r in rater_list:
            # username = (names.get_first_name()+str(r.id)
            # u = User.objects.create_user(username, username + "@gmail.com", "PASSWORD")
            u = User.objects.create_user(r.id, "test@gmail.com", "PASSWORD")
            u.save()
            r.user = u
            r.save()

    dependencies = [
        ('movielens_app', '0006_auto_20170322_2205'),
    ]

    operations = [
        migrations.RunPython(load_users),
    ]
